<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CoachCompanion.Audio\CoachCompanion.Audio.csproj" />
    <ProjectReference Include="..\..\src\CoachCompanion.Audio.Windows\CoachCompanion.Audio.Windows.csproj" />
    <ProjectReference Include="..\..\src\CoachCompanion.Speech\CoachCompanion.Speech.csproj" />
    <ProjectReference Include="..\..\src\CoachCompanion.Core\CoachCompanion.Core.csproj" />
    <ProjectReference Include="..\..\src\CoachCompanion.Audio.WebRtc\CoachCompanion.Audio.WebRtc.csproj" />
  </ItemGroup>

</Project>
