<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoachCompanion.Audio\CoachCompanion.Audio.csproj" />
    <ProjectReference Include="..\CoachCompanion.Speech\CoachCompanion.Speech.csproj" />
  </ItemGroup>

</Project>
